# Generated by Django 5.2.5 on 2025-09-09 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('flight', 'Flight'), ('accommodation', 'Accommodation'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('place_id', models.CharField(db_index=True, help_text='Google Place ID', max_length=255)),
                ('place_name', models.CharField(help_text='Primary display name from Places (e.g., venue/hotel/airport)', max_length=200)),
                ('formatted_address', models.CharField(help_text='Formatted address from Places', max_length=255)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('raw_place', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items_created', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.trip')),
            ],
            options={
                'ordering': ['date', 'start_time', 'item_type', 'place_name'],
                'indexes': [models.Index(fields=['trip', 'date'], name='trips_tripi_trip_id_84675e_idx'), models.Index(fields=['item_type'], name='trips_tripi_item_ty_e3ea70_idx'), models.Index(fields=['place_id'], name='trips_tripi_place_i_f7ace5_idx')],
            },
        ),
    ]
