# Generated by Django 5.2.5 on 2025-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, help_text='Human-friendly identifier for URLs (not yet enforced unique).', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Stable public identifier (will replace numeric id in URLs).', null=True),
        ),
    ]
