# Generated by Django 5.2.5 on 2025-09-29 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_backfill_trip_uid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable public identifier (will replace numeric id in URLs).', null=True),
        ),
    ]
