# Generated by Django 5.2.5 on 2025-10-01 10:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(choices=[('google', 'Google Places'), ('manual', 'Manual'), ('osm', 'OpenStreetMap')], default='google', max_length=10)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('city_name', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('raw_place', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['guest_id', 'expires_at'], name='trips_guest_guest_i_5a171c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='guest_trip_end_on_or_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('place_id__gt', ''), ('source', 'google')), models.Q(('source', 'google'), _negated=True), _connector='OR'), name='guest_trip_google_requires_place_id'), models.CheckConstraint(condition=models.Q(models.Q(('city_name__gt', ''), ('lat__isnull', False), ('lng__isnull', False), ('source', 'manual')), models.Q(('source', 'manual'), _negated=True), _connector='OR'), name='guest_trip_manual_requires_min_fields')],
            },
        ),
        migrations.CreateModel(
            name='GuestTripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('flight', 'Flight'), ('accommodation', 'Accommodation'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('place_id', models.CharField(db_index=True, help_text='Google Place ID', max_length=255)),
                ('place_name', models.CharField(help_text='Primary display name from Places', max_length=200)),
                ('formatted_address', models.CharField(help_text='Formatted address from Places', max_length=255)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('raw_place', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_trip_items_created', to=settings.AUTH_USER_MODEL)),
                ('guest_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.guesttrip')),
            ],
            options={
                'ordering': ['date', 'start_time', 'item_type', 'place_name'],
                'indexes': [models.Index(fields=['guest_trip', 'date'], name='trips_guest_guest_t_810895_idx'), models.Index(fields=['item_type'], name='trips_guest_item_ty_049e21_idx'), models.Index(fields=['place_id'], name='trips_guest_place_i_2c50ef_idx')],
            },
        ),
    ]
